version: '3'

services:
  opentripplanner:
    #image: mfdz/opentripplanner:d38ffb9c2d7c52ff1f89423b077714e4a2c8d5de
    image: mfdz/opentripplanner:latest
    restart: on-failure:5
    container_name: opentripplanner
    logging:
      driver: journald
    ports:
      - 8080:8080
    command: --load --serve graph
    environment:
      - ROUTER_NAME=hb
      - API_URL=https://api.stadtnavi.de/otp/
      - JAVA_OPTS=-Xmx20G -XX:+FlightRecorder
    volumes:
      - /var/graph-build/latest/:/opt/opentripplanner/graph/

networks:
  digitransit:
    # all default
