---

- name: Apply the digitransit stack
  hosts: all
  become: yes
  roles:
    - base
    - matomo
    - delay-prediction-service
    - digitransit
    - thingsboard-enhancer
    - thingsboard-to-mqtt
