---
- name: Install systemd files
  template:
    src: '{{ item }}'
    dest: /etc/systemd/system/
  with_items:
    - thingsboard-to-mqtt.service
  notify: Restart thingsboard-to-mqtt

- name: Start thingsboard-to-mqtt
  systemd:
    name: thingsboard-to-mqtt.service
    state: started
    daemon_reload: yes
  when: enable_prediction_service == false

- name: Stop thingsboard-to-mqtt
  systemd:
    name: thingsboard-to-mqtt.service
    state: stopped
    daemon_reload: yes
  when: enable_prediction_service