---
- name: Creates directory
  file:
    path: /var/thingsboard/herrenberg/{{ item }}/
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  with_items:
    - "charging-stations"
    - "road-disruptions"
    - parking
    - weather
    - taxi

- name: Copy CIFS file
  template:
    src: "{{ item }}"
    dest: /var/thingsboard/herrenberg/road-disruptions/
  with_items:
    - road-disruptions.cifs.json
    - road-disruptions.corrected.cifs.json

- name: Copy OBB ParkAPI file
  template:
    src: "{{ item }}"
    dest: /var/thingsboard/herrenberg/parking/
  with_items:
    - open-bike-box.json

- name: Install systemd files
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/
  with_items:
    - thingsboard-enhancer.service
    - thingsboard-enhancer.timer

- name: Start thingsboard timer
  systemd:
    name: thingsboard-enhancer.timer
    state: started
    enabled: yes
    daemon_reload: yes

- name: Download thingsboard-to-parkapi script
  get_url:
    url: https://raw.githubusercontent.com/mfdz/thingsboard-to-parkapi/{{ thingsboard_to_parkapi_commit }}/thingsboard-to-parkapi
    dest: /usr/local/bin/thingsboard-to-parkapi
    mode: 711

- name: Creates directory
  file:
    path: /var/parkapi/
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Download static parking_lots.geojson file
  get_url:
    url: https://raw.githubusercontent.com/mfdz/thingsboard-to-parkapi/{{ thingsboard_to_parkapi_commit }}/parking_lots.geojson
    dest: /var/parkapi
    owner: www-data
    group: www-data
    mode: 0775

- name: Install systemd files
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - thingsboard-to-parkapi.service
    - thingsboard-to-parkapi.timer

- name: Start thingsboard timer
  systemd:
    name: thingsboard-to-parkapi.timer
    state: started
    enabled: yes
    daemon_reload: yes


