---
- name: Create tile cache directory
  file:
    path: /var/cache/nginx
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Copy nginx site conf
  template: src=nginx-site.conf dest=/etc/nginx/sites-enabled/{{item}}.conf
  with_items:
    - "{{ tiles_hostname }}"
  notify: Restart nginx

- name: Copy unauthorized.png
  copy:
    src: unauthorized.png
    dest: /usr/share/nginx/html/

- name: Create working dir directory
  file:
    path: /var/tileserver/
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Download and unzip fonts
  ansible.builtin.unarchive:
    src: https://github.com/klokantech/klokantech-gl-fonts/archive/refs/tags/v1.0.0.zip
    dest: /var/tileserver/
    remote_src: yes
    creates: /var/tileserver/klokantech-gl-fonts-1.0.0

- name: Copy sprites
  ansible.builtin.copy:
    src: sprites
    dest: /var/tileserver/

- name: Symlink fonts
  ansible.builtin.file:
    dest: /var/tileserver/fonts
    src: klokantech-gl-fonts-1.0.0
    state: link

- name: Install config and script files
  template: src={{ item }} dest=/var/tileserver/
  with_items:
    - streets.json
    - satellite-overlay.json
    - bicycle.json
    - tileserver-config.json
  notify: Restart tileserver

- name: Install systemd files
  template:
    src: "systemd/{{ item }}"
    dest: /etc/systemd/system/
  with_items:
    - tileserver.service
    - tileserver-restart.service
    - tileserver-restart.timer
  notify: Restart tileserver

- name: Start tileserver and restart every night
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - tileserver.service
    - tileserver-restart.timer

- apt_repository:
    repo: "deb http://deb.debian.org/debian buster-backports main contrib non-free"
    state: present
    update_cache: yes

- name: Install monit from backports
  apt:
    name: monit
    state: present
    default_release: buster-backports

- name: Copy monit file
  template: src=monit.check dest=/etc/monit/conf-enabled/tileserver.cfg
  notify: Restart monit

- name: Set monit to check every 30 seconds
  lineinfile:
    path: /etc/monit/monitrc
    regexp: 'set daemon'
    line: "set daemon 30 # check every 30 seconds"
  notify: Restart monit

- name: Start monit
  service:
    name: monit
    state: started

